### ISSUE TITLE
Add support for Laravel 6.0

### ISSUE THREAD

**Issue by vaites** [KristofMorva/laravel-ide-macros#11]
Laravel 6.0 is just released and composer.json restricts to 5 branch.

**Comment by nuernbergerA** [comment]
@KristofMorva can you pls have a look at this?

**Comment by KristofMorva** [comment]
@nuernbergerA sorry, I got no notification from any of the issues or PRs in this repository until you mentioned be, even though I'm watching it, not sure what is set up wrong.

I'll check out all of them at night!
