### ISSUE TITLE
ErrorException  : Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by DanielLavoie90** [KristofMorva/laravel-ide-macros#15]
```
class ReflectionType
{
	/**
	 * To string
	 * @link https://php.net/manual/en/reflectiontype.tostring.php
	 * @return string Returns the type of the parameter.
	 * @since 7.0
	 * @deprecated 7.1 Please use getName()
	 * @see \ReflectionType::getName()
	 */
	public function __toString()
	{
	}
}
```

Adding getName() after getType() on line 178 of MacrosCommand seems to fix the problem.

`$this->write($parameter->getType()->getName() . " ");`

**Comment by KristofMorva** [comment]
Hey, did you happen to investigate which PHP version `GetType`'s `GetName` is available from? Just to make sure that the change does not break older PHP versions :)

**Comment by Teakowa** [comment]
`getName` only support PHP>=7.1.0 [ReflectionNamedType::getName](https://www.php.net/manual/en/reflectionnamedtype.getname.php)

**Comment by KristofMorva** [comment]
Thank you for letting me know.
Let's fix this warning in a next major version to make sure that it does not affect people with older PHP versions.

Does any of you have the time for a PR & testing it out if it works the same, properly? Sorry for not being able to do it myself, but I don't have a web development environment right now :)

**Comment by Teakowa** [comment]
Reflection is a new feature in PHP 7.0, and the  in the package makes it impossible to use this package for versions < PHP 7.0.

So, it seems that from the beginning this package was not supported < Laravel version 5.5? xD

**Comment by Teakowa** [comment]
`ReflectionParameter::getType` is a new feature in PHP 7.0, and the in the package makes it impossible to use this package for versions < PHP 7.0.

So, it seems that from the beginning this package was not supported < Laravel version 5.5? xD

**Comment by KristofMorva** [comment]
Hmm, if I remember right I wrote and used this package with Laravel 5.4.

**Comment by Teakowa** [comment]
Perhaps your Laravel 5.4 is running on PHP 7?

Because I'm running Laravel 5.4 with PHP 5.6 get an  error.

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/27560638/78528898-0f063c00-7813-11ea-9933-bfeafa225b66.png">

```bash
PHP Fatal error:  Call to undefined method ReflectionFunction::getReturnType() in /var/www/5.4/vendor/tutorigo/laravel-ide-macros/src/Console/MacrosCommand.php on line 110

In MacrosCommand.php line 110:

  Call to undefined method ReflectionFunction::getReturnType()

```

[ReflectionFunction::getReturnType](https://www.php.net/manual/en/reflectionfunctionabstract.getreturntype.php) only support PHP 7 too. xD

**Comment by KristofMorva** [comment]
Hmmm alright, thanks for checking it out, then it should be safe to require PHP 7.0 in the next patch version, and integrate a PR for this issue with PHP 7.1 requirement in a new major version.

**Comment by KristofMorva** [comment]
#19 should solve it
