### ISSUE TITLE
Add support Laravel 7

### ISSUE THREAD

**Issue by Teakowa** [KristofMorva/laravel-ide-macros#16]
Laravel 7 is released, but composer.json restricts to 5 and 6.

**Comment by KristofMorva** [comment]
Hey, thanks for letting me know, however, I'm currently not working in web development. Are there any structural changes which impact this package (so is the only problem the composer restriction, or does the logic need an overhaul)?

**Comment by Teakowa** [comment]
I tested in my project (PHP 7.4 Laravel 7.4 with #15), seems to working.

If just add Laravel 7 support, I think just need to add `^7.0` in require.

PS: I recommend change the minimum support to `^5.5`,

**Comment by KristofMorva** [comment]
> PS: I recommend change the minimum support to `^5.5`,

Hey, thank you, is there any reason for it? Between 5.0 and 5.5 it has issues?

**Comment by Teakowa** [comment]
> > PS: I recommend change the minimum support to `^5.5`,
> 
> Hey, thank you, is there any reason for it? Between 5.0 and 5.5 it has issues?

5.0 require `PHP >= 5.4.0`, and last commit is Mar 18 2016, that is a long time ago.

5.5 is a LTS verison(last LTS is 6), require `PHP >= 7.0`, and its security update supports to August 30 2020.

So I don't think we need to support such an old version, do you think?

**Comment by KristofMorva** [comment]
Well, although that's true, until it does not cause any issues, I'd keep it in just in case there'd be someone who is stuck on an older version for any reason (too big project to port, restrictive company environment, etc etc).
