### ISSUE TITLE
Not compatible with PHP 7.4

### ISSUE THREAD

**Issue by willsmanley** [KristofMorva/laravel-ide-macros#18]
Function ReflectionType::__toString() is deprecated

**Comment by willsmanley** [comment]
Specifically it is line 178 and line 191 in the latest version of MacrosCommand.php:
```
$this->write($parameter->getType() . " ");
$this->write(": $returnType");
```
I forked the library so I could comment out those parts and it hasn't affected my ability to generate a good helper file since those two parts aren't essential for autocompletion.

**Comment by KristofMorva** [comment]
It's a duplication of #15 (which also has a proposed solution)
