### ISSUE TITLE
Return typehits of primitive values

### ISSUE THREAD

**Issue by mikemand** [KristofMorva/laravel-ide-macros#21]
It looks like the return typehints that are primitive values (`bool`, `array`, `string`, etc.) are being handled like they need a namespace. For example:

```php
public static function validate($callback): \bool {
```

or

```php
public static function pluckToArray($value, $key = NULL): \array {
```

This doesn't seem to matter for `bool`. However, if the return is `array`, prefixing it with a backslash causes the interpreter to freak out and nothing after that line is interpreted by the IDE. The error messages my IDE throw are: "Method should either have body or be abstract" and "Unexpected: array".

To reproduce, create a new Laravel app and install your package and [Spatie's Collection Macros](https://github.com/spatie/laravel-collection-macros):

```bash
laravel new ide-macro-test && \
cd ide-macro-test && \
composer require spatie/laravel-collection-macros tutorigo/laravel-ide-macros && \
php artisan ide-helper:macros
```

Check line 72 of `_ide_macros.php`.

**Comment by KristofMorva** [comment]
Thanks for letting us know, probably PR #19 broke it.
